<?php
namespace App\OpenApi\Paths;
use OpenApi\Attributes as OA;
class BiometricoPaths {
#[OA\Get(path:'/api/v1/biometricos',summary:'index',description:'Permiso requerido: biometricos.ver.',security:[['sanctumBearer'=>[]]],tags:['Biométricos'],responses:[new OA\Response(response:200,description:'OK'),new OA\Response(response:401,description:'No autenticado'),new OA\Response(response:403,description:'Sin permiso'),new OA\Response(response:404,description:'No encontrado'),new OA\Response(response:422,description:'Datos inválidos')])] public function index():void{}
#[OA\Post(path:'/api/v1/biometricos/enrolar',summary:'enrolar',description:'Permiso requerido: biometricos.enrolar.',security:[['sanctumBearer'=>[]]],tags:['Biométricos'],requestBody:new OA\RequestBody(required:true,content:new OA\JsonContent(type:'object')),responses:[new OA\Response(response:200,description:'OK'),new OA\Response(response:401,description:'No autenticado'),new OA\Response(response:403,description:'Sin permiso'),new OA\Response(response:404,description:'No encontrado'),new OA\Response(response:422,description:'Datos inválidos')])] public function enrolar():void{}
#[OA\Get(path:'/api/v1/biometricos/{biometrico}',summary:'show',description:'Permiso requerido: biometricos.ver.',security:[['sanctumBearer'=>[]]],tags:['Biométricos'],parameters:[new OA\Parameter(name:'biometrico',in:'path',required:true,schema:new OA\Schema(type:'integer'))],responses:[new OA\Response(response:200,description:'OK'),new OA\Response(response:401,description:'No autenticado'),new OA\Response(response:403,description:'Sin permiso'),new OA\Response(response:404,description:'No encontrado'),new OA\Response(response:422,description:'Datos inválidos')])] public function show():void{}
#[OA\Patch(path:'/api/v1/biometricos/{biometrico}/desactivar',summary:'desactivar',description:'Permiso requerido: biometricos.eliminar.',security:[['sanctumBearer'=>[]]],tags:['Biométricos'],parameters:[new OA\Parameter(name:'biometrico',in:'path',required:true,schema:new OA\Schema(type:'integer'))],responses:[new OA\Response(response:200,description:'OK'),new OA\Response(response:401,description:'No autenticado'),new OA\Response(response:403,description:'Sin permiso'),new OA\Response(response:404,description:'No encontrado'),new OA\Response(response:422,description:'Datos inválidos')])] public function desactivar():void{}
#[OA\Patch(path:'/api/v1/biometricos/{biometrico}/marcar-principal',summary:'marcarPrincipal',description:'Permiso requerido: biometricos.enrolar.',security:[['sanctumBearer'=>[]]],tags:['Biométricos'],parameters:[new OA\Parameter(name:'biometrico',in:'path',required:true,schema:new OA\Schema(type:'integer'))],responses:[new OA\Response(response:200,description:'OK'),new OA\Response(response:401,description:'No autenticado'),new OA\Response(response:403,description:'Sin permiso'),new OA\Response(response:404,description:'No encontrado'),new OA\Response(response:422,description:'Datos inválidos')])] public function marcarPrincipal():void{}
#[OA\Patch(path:'/api/v1/biometricos/{biometrico}/revocar',summary:'revocar',description:'Permiso requerido: biometricos.eliminar.',security:[['sanctumBearer'=>[]]],tags:['Biométricos'],parameters:[new OA\Parameter(name:'biometrico',in:'path',required:true,schema:new OA\Schema(type:'integer'))],responses:[new OA\Response(response:200,description:'OK'),new OA\Response(response:401,description:'No autenticado'),new OA\Response(response:403,description:'Sin permiso'),new OA\Response(response:404,description:'No encontrado'),new OA\Response(response:422,description:'Datos inválidos')])] public function revocar():void{}
}