<?php
namespace App\OpenApi\Paths; use OpenApi\Attributes as OA;
class ClientePaths {
#[OA\Get(path:'/api/v1/clientes',summary:'Listar clientes',description:'Permiso requerido: clientes.ver.',security:[['sanctumBearer'=>[]]],tags:['Clientes'],parameters:[new OA\Parameter(name:'q',in:'query',schema:new OA\Schema(type:'string')),new OA\Parameter(name:'sucursal_id',in:'query',schema:new OA\Schema(type:'integer')),new OA\Parameter(name:'estatus',in:'query',schema:new OA\Schema(type:'string')),new OA\Parameter(name:'activo',in:'query',schema:new OA\Schema(type:'string',enum:['true','false','all'])),new OA\Parameter(name:'page',in:'query',schema:new OA\Schema(type:'integer')),new OA\Parameter(name:'per_page',in:'query',schema:new OA\Schema(type:'integer'))],responses:[new OA\Response(response:200,description:'Clientes obtenidos correctamente'),new OA\Response(response:401,description:'No autenticado'),new OA\Response(response:403,description:'Sin permiso')])] public function index():void{}
#[OA\Post(path:'/api/v1/clientes',summary:'Crear cliente',description:'Permiso requerido: clientes.crear.',security:[['sanctumBearer'=>[]]],tags:['Clientes'],requestBody:new OA\RequestBody(required:true,content:new OA\JsonContent(type:'object')),responses:[new OA\Response(response:201,description:'Cliente creado'),new OA\Response(response:422,description:'Datos inválidos')])] public function store():void{}
#[OA\Get(path:'/api/v1/clientes/{cliente}',summary:'Ver cliente',description:'Permiso requerido: clientes.ver.',security:[['sanctumBearer'=>[]]],tags:['Clientes'],parameters:[new OA\Parameter(name:'cliente',in:'path',required:true,schema:new OA\Schema(type:'integer'))],responses:[new OA\Response(response:200,description:'Cliente obtenido'),new OA\Response(response:404,description:'No encontrado')])] public function show():void{}
#[OA\Put(path:'/api/v1/clientes/{cliente}',summary:'Actualizar cliente (PUT)',description:'Permiso requerido: clientes.editar.',security:[['sanctumBearer'=>[]]],tags:['Clientes'],parameters:[new OA\Parameter(name:'cliente',in:'path',required:true,schema:new OA\Schema(type:'integer'))],requestBody:new OA\RequestBody(required:true,content:new OA\JsonContent(type:'object')),responses:[new OA\Response(response:200,description:'Cliente actualizado')])] public function updatePut():void{}
#[OA\Patch(path:'/api/v1/clientes/{cliente}',summary:'Actualizar cliente (PATCH)',description:'Permiso requerido: clientes.editar.',security:[['sanctumBearer'=>[]]],tags:['Clientes'],parameters:[new OA\Parameter(name:'cliente',in:'path',required:true,schema:new OA\Schema(type:'integer'))],requestBody:new OA\RequestBody(required:true,content:new OA\JsonContent(type:'object')),responses:[new OA\Response(response:200,description:'Cliente actualizado')])] public function updatePatch():void{}
#[OA\Patch(path:'/api/v1/clientes/{cliente}/cambiar-estatus',summary:'Cambiar estatus',description:'Permiso requerido: clientes.cambiar_estatus.',security:[['sanctumBearer'=>[]]],tags:['Clientes'],parameters:[new OA\Parameter(name:'cliente',in:'path',required:true,schema:new OA\Schema(type:'integer'))],responses:[new OA\Response(response:200,description:'Estatus actualizado')])] public function cambiarEstatus():void{}
#[OA\Patch(path:'/api/v1/clientes/{cliente}/desactivar',summary:'Desactivar cliente',description:'Permiso requerido: clientes.desactivar.',security:[['sanctumBearer'=>[]]],tags:['Clientes'],parameters:[new OA\Parameter(name:'cliente',in:'path',required:true,schema:new OA\Schema(type:'integer'))],responses:[new OA\Response(response:200,description:'Cliente desactivado')])] public function desactivar():void{}
#[OA\Patch(path:'/api/v1/clientes/{cliente}/reactivar',summary:'Reactivar cliente',description:'Permiso requerido: clientes.cambiar_estatus.',security:[['sanctumBearer'=>[]]],tags:['Clientes'],parameters:[new OA\Parameter(name:'cliente',in:'path',required:true,schema:new OA\Schema(type:'integer'))],responses:[new OA\Response(response:200,description:'Cliente reactivado')])] public function reactivar():void{}
#[OA\Get(path:'/api/v1/clientes/{cliente}/membresias',summary:'Membresías por cliente',description:'Permiso requerido: membresias.ver.',security:[['sanctumBearer'=>[]]],tags:['Clientes'],parameters:[new OA\Parameter(name:'cliente',in:'path',required:true,schema:new OA\Schema(type:'integer'))],responses:[new OA\Response(response:200,description:'Membresías obtenidas')])] public function membresias():void{}
#[OA\Get(path:'/api/v1/clientes/{cliente}/pagos',summary:'Pagos por cliente',description:'Permiso requerido: pagos.ver.',security:[['sanctumBearer'=>[]]],tags:['Clientes'],parameters:[new OA\Parameter(name:'cliente',in:'path',required:true,schema:new OA\Schema(type:'integer'))],responses:[new OA\Response(response:200,description:'Pagos obtenidos')])] public function pagos():void{}
#[OA\Get(path:'/api/v1/clientes/{cliente}/accesos',summary:'Accesos por cliente',description:'Permiso requerido: accesos.ver.',security:[['sanctumBearer'=>[]]],tags:['Clientes'],parameters:[new OA\Parameter(name:'cliente',in:'path',required:true,schema:new OA\Schema(type:'integer'))],responses:[new OA\Response(response:200,description:'Accesos obtenidos')])] public function accesos():void{}
#[OA\Get(path:'/api/v1/clientes/{cliente}/biometricos',summary:'Biométricos por cliente',description:'Permiso requerido: biometricos.ver.',security:[['sanctumBearer'=>[]]],tags:['Clientes'],parameters:[new OA\Parameter(name:'cliente',in:'path',required:true,schema:new OA\Schema(type:'integer'))],responses:[new OA\Response(response:200,description:'Biométricos obtenidos')])] public function biometricos():void{}
}
