<?php
namespace App\OpenApi\Paths;
use OpenApi\Attributes as OA;
class CorteCajaPaths {
#[OA\Get(path:'/api/v1/cortes-caja',summary:'index',description:'Permiso requerido: pagos.ver.',security:[['sanctumBearer'=>[]]],tags:['Cortes de Caja'],responses:[new OA\Response(response:200,description:'OK'),new OA\Response(response:401,description:'No autenticado'),new OA\Response(response:403,description:'Sin permiso'),new OA\Response(response:404,description:'No encontrado'),new OA\Response(response:422,description:'Datos inválidos')])] public function index():void{}
#[OA\Post(path:'/api/v1/cortes-caja',summary:'store',description:'Permiso requerido: pagos.registrar.',security:[['sanctumBearer'=>[]]],tags:['Cortes de Caja'],requestBody:new OA\RequestBody(required:true,content:new OA\JsonContent(type:'object')),responses:[new OA\Response(response:200,description:'OK'),new OA\Response(response:401,description:'No autenticado'),new OA\Response(response:403,description:'Sin permiso'),new OA\Response(response:404,description:'No encontrado'),new OA\Response(response:422,description:'Datos inválidos')])] public function store():void{}
#[OA\Post(path:'/api/v1/cortes-caja/calcular',summary:'calcular',description:'Permiso requerido: pagos.ver.',security:[['sanctumBearer'=>[]]],tags:['Cortes de Caja'],requestBody:new OA\RequestBody(required:true,content:new OA\JsonContent(type:'object')),responses:[new OA\Response(response:200,description:'OK'),new OA\Response(response:401,description:'No autenticado'),new OA\Response(response:403,description:'Sin permiso'),new OA\Response(response:404,description:'No encontrado'),new OA\Response(response:422,description:'Datos inválidos')])] public function calcular():void{}
#[OA\Get(path:'/api/v1/cortes-caja/{corte}',summary:'show',description:'Permiso requerido: pagos.ver.',security:[['sanctumBearer'=>[]]],tags:['Cortes de Caja'],parameters:[new OA\Parameter(name:'corte',in:'path',required:true,schema:new OA\Schema(type:'integer'))],responses:[new OA\Response(response:200,description:'OK'),new OA\Response(response:401,description:'No autenticado'),new OA\Response(response:403,description:'Sin permiso'),new OA\Response(response:404,description:'No encontrado'),new OA\Response(response:422,description:'Datos inválidos')])] public function show():void{}
#[OA\Patch(path:'/api/v1/cortes-caja/{corte}/cancelar',summary:'cancelar',description:'Permiso requerido: pagos.cancelar.',security:[['sanctumBearer'=>[]]],tags:['Cortes de Caja'],parameters:[new OA\Parameter(name:'corte',in:'path',required:true,schema:new OA\Schema(type:'integer'))],responses:[new OA\Response(response:200,description:'OK'),new OA\Response(response:401,description:'No autenticado'),new OA\Response(response:403,description:'Sin permiso'),new OA\Response(response:404,description:'No encontrado'),new OA\Response(response:422,description:'Datos inválidos')])] public function cancelar():void{}
#[OA\Get(path:'/api/v1/cortes-caja/{corte}/exportar',summary:'exportar',description:'Permiso requerido: reportes.exportar.',security:[['sanctumBearer'=>[]]],tags:['Cortes de Caja'],parameters:[new OA\Parameter(name:'corte',in:'path',required:true,schema:new OA\Schema(type:'integer'))],responses:[new OA\Response(response:200,description:'OK'),new OA\Response(response:401,description:'No autenticado'),new OA\Response(response:403,description:'Sin permiso'),new OA\Response(response:404,description:'No encontrado'),new OA\Response(response:422,description:'Datos inválidos')])] public function exportar():void{}
}