<?php
namespace App\OpenApi\Paths;
use OpenApi\Attributes as OA;
class DispositivoPaths {
#[OA\Get(path:'/api/v1/dispositivos',summary:'index',description:'Permiso requerido: dispositivos.ver.',security:[['sanctumBearer'=>[]]],tags:['Dispositivos'],responses:[new OA\Response(response:200,description:'OK'),new OA\Response(response:401,description:'No autenticado'),new OA\Response(response:403,description:'Sin permiso'),new OA\Response(response:404,description:'No encontrado'),new OA\Response(response:422,description:'Datos inválidos')])] public function index():void{}
#[OA\Post(path:'/api/v1/dispositivos',summary:'store',description:'Permiso requerido: dispositivos.crear.',security:[['sanctumBearer'=>[]]],tags:['Dispositivos'],requestBody:new OA\RequestBody(required:true,content:new OA\JsonContent(type:'object')),responses:[new OA\Response(response:200,description:'OK'),new OA\Response(response:401,description:'No autenticado'),new OA\Response(response:403,description:'Sin permiso'),new OA\Response(response:404,description:'No encontrado'),new OA\Response(response:422,description:'Datos inválidos')])] public function store():void{}
#[OA\Get(path:'/api/v1/dispositivos/{dispositivo}',summary:'show',description:'Permiso requerido: dispositivos.ver.',security:[['sanctumBearer'=>[]]],tags:['Dispositivos'],parameters:[new OA\Parameter(name:'dispositivo',in:'path',required:true,schema:new OA\Schema(type:'integer'))],responses:[new OA\Response(response:200,description:'OK'),new OA\Response(response:401,description:'No autenticado'),new OA\Response(response:403,description:'Sin permiso'),new OA\Response(response:404,description:'No encontrado'),new OA\Response(response:422,description:'Datos inválidos')])] public function show():void{}
#[OA\Put(path:'/api/v1/dispositivos/{dispositivo}',summary:'updatePut',description:'Permiso requerido: dispositivos.editar.',security:[['sanctumBearer'=>[]]],tags:['Dispositivos'],parameters:[new OA\Parameter(name:'dispositivo',in:'path',required:true,schema:new OA\Schema(type:'integer'))],requestBody:new OA\RequestBody(required:true,content:new OA\JsonContent(type:'object')),responses:[new OA\Response(response:200,description:'OK'),new OA\Response(response:401,description:'No autenticado'),new OA\Response(response:403,description:'Sin permiso'),new OA\Response(response:404,description:'No encontrado'),new OA\Response(response:422,description:'Datos inválidos')])] public function updatePut():void{}
#[OA\Patch(path:'/api/v1/dispositivos/{dispositivo}',summary:'updatePatch',description:'Permiso requerido: dispositivos.editar.',security:[['sanctumBearer'=>[]]],tags:['Dispositivos'],parameters:[new OA\Parameter(name:'dispositivo',in:'path',required:true,schema:new OA\Schema(type:'integer'))],requestBody:new OA\RequestBody(required:true,content:new OA\JsonContent(type:'object')),responses:[new OA\Response(response:200,description:'OK'),new OA\Response(response:401,description:'No autenticado'),new OA\Response(response:403,description:'Sin permiso'),new OA\Response(response:404,description:'No encontrado'),new OA\Response(response:422,description:'Datos inválidos')])] public function updatePatch():void{}
#[OA\Patch(path:'/api/v1/dispositivos/{dispositivo}/cambiar-estatus',summary:'cambiarEstatus',description:'Permiso requerido: dispositivos.editar.',security:[['sanctumBearer'=>[]]],tags:['Dispositivos'],parameters:[new OA\Parameter(name:'dispositivo',in:'path',required:true,schema:new OA\Schema(type:'integer'))],responses:[new OA\Response(response:200,description:'OK'),new OA\Response(response:401,description:'No autenticado'),new OA\Response(response:403,description:'Sin permiso'),new OA\Response(response:404,description:'No encontrado'),new OA\Response(response:422,description:'Datos inválidos')])] public function cambiarEstatus():void{}
#[OA\Patch(path:'/api/v1/dispositivos/{dispositivo}/desactivar',summary:'desactivar',description:'Permiso requerido: dispositivos.desactivar.',security:[['sanctumBearer'=>[]]],tags:['Dispositivos'],parameters:[new OA\Parameter(name:'dispositivo',in:'path',required:true,schema:new OA\Schema(type:'integer'))],responses:[new OA\Response(response:200,description:'OK'),new OA\Response(response:401,description:'No autenticado'),new OA\Response(response:403,description:'Sin permiso'),new OA\Response(response:404,description:'No encontrado'),new OA\Response(response:422,description:'Datos inválidos')])] public function desactivar():void{}
#[OA\Patch(path:'/api/v1/dispositivos/{dispositivo}/reactivar',summary:'reactivar',description:'Permiso requerido: dispositivos.editar.',security:[['sanctumBearer'=>[]]],tags:['Dispositivos'],parameters:[new OA\Parameter(name:'dispositivo',in:'path',required:true,schema:new OA\Schema(type:'integer'))],responses:[new OA\Response(response:200,description:'OK'),new OA\Response(response:401,description:'No autenticado'),new OA\Response(response:403,description:'Sin permiso'),new OA\Response(response:404,description:'No encontrado'),new OA\Response(response:422,description:'Datos inválidos')])] public function reactivar():void{}
}