<?php
namespace App\OpenApi\Paths;
use OpenApi\Attributes as OA;
class MembresiaPaths {
#[OA\Get(path:'/api/v1/membresias',summary:'index',description:'Permiso requerido: membresias.ver.',security:[['sanctumBearer'=>[]]],tags:['Membresías'],responses:[new OA\Response(response:200,description:'OK'),new OA\Response(response:401,description:'No autenticado'),new OA\Response(response:403,description:'Sin permiso'),new OA\Response(response:404,description:'No encontrado'),new OA\Response(response:422,description:'Datos inválidos')])] public function index():void{}
#[OA\Post(path:'/api/v1/membresias',summary:'store',description:'Permiso requerido: membresias.crear.',security:[['sanctumBearer'=>[]]],tags:['Membresías'],requestBody:new OA\RequestBody(required:true,content:new OA\JsonContent(type:'object')),responses:[new OA\Response(response:200,description:'OK'),new OA\Response(response:401,description:'No autenticado'),new OA\Response(response:403,description:'Sin permiso'),new OA\Response(response:404,description:'No encontrado'),new OA\Response(response:422,description:'Datos inválidos')])] public function store():void{}
#[OA\Get(path:'/api/v1/membresias/{membresia}',summary:'show',description:'Permiso requerido: membresias.ver.',security:[['sanctumBearer'=>[]]],tags:['Membresías'],parameters:[new OA\Parameter(name:'membresia',in:'path',required:true,schema:new OA\Schema(type:'integer'))],responses:[new OA\Response(response:200,description:'OK'),new OA\Response(response:401,description:'No autenticado'),new OA\Response(response:403,description:'Sin permiso'),new OA\Response(response:404,description:'No encontrado'),new OA\Response(response:422,description:'Datos inválidos')])] public function show():void{}
#[OA\Put(path:'/api/v1/membresias/{membresia}',summary:'updatePut',description:'Permiso requerido: membresias.editar.',security:[['sanctumBearer'=>[]]],tags:['Membresías'],parameters:[new OA\Parameter(name:'membresia',in:'path',required:true,schema:new OA\Schema(type:'integer'))],requestBody:new OA\RequestBody(required:true,content:new OA\JsonContent(type:'object')),responses:[new OA\Response(response:200,description:'OK'),new OA\Response(response:401,description:'No autenticado'),new OA\Response(response:403,description:'Sin permiso'),new OA\Response(response:404,description:'No encontrado'),new OA\Response(response:422,description:'Datos inválidos')])] public function updatePut():void{}
#[OA\Patch(path:'/api/v1/membresias/{membresia}',summary:'updatePatch',description:'Permiso requerido: membresias.editar.',security:[['sanctumBearer'=>[]]],tags:['Membresías'],parameters:[new OA\Parameter(name:'membresia',in:'path',required:true,schema:new OA\Schema(type:'integer'))],requestBody:new OA\RequestBody(required:true,content:new OA\JsonContent(type:'object')),responses:[new OA\Response(response:200,description:'OK'),new OA\Response(response:401,description:'No autenticado'),new OA\Response(response:403,description:'Sin permiso'),new OA\Response(response:404,description:'No encontrado'),new OA\Response(response:422,description:'Datos inválidos')])] public function updatePatch():void{}
#[OA\Patch(path:'/api/v1/membresias/{membresia}/cancelar',summary:'cancelar',description:'Permiso requerido: membresias.cancelar.',security:[['sanctumBearer'=>[]]],tags:['Membresías'],parameters:[new OA\Parameter(name:'membresia',in:'path',required:true,schema:new OA\Schema(type:'integer'))],responses:[new OA\Response(response:200,description:'OK'),new OA\Response(response:401,description:'No autenticado'),new OA\Response(response:403,description:'Sin permiso'),new OA\Response(response:404,description:'No encontrado'),new OA\Response(response:422,description:'Datos inválidos')])] public function cancelar():void{}
#[OA\Patch(path:'/api/v1/membresias/{membresia}/reactivar',summary:'reactivar',description:'Permiso requerido: membresias.editar.',security:[['sanctumBearer'=>[]]],tags:['Membresías'],parameters:[new OA\Parameter(name:'membresia',in:'path',required:true,schema:new OA\Schema(type:'integer'))],responses:[new OA\Response(response:200,description:'OK'),new OA\Response(response:401,description:'No autenticado'),new OA\Response(response:403,description:'Sin permiso'),new OA\Response(response:404,description:'No encontrado'),new OA\Response(response:422,description:'Datos inválidos')])] public function reactivar():void{}
#[OA\Patch(path:'/api/v1/membresias/{membresia}/renovar',summary:'renovar',description:'Permiso requerido: membresias.renovar.',security:[['sanctumBearer'=>[]]],tags:['Membresías'],parameters:[new OA\Parameter(name:'membresia',in:'path',required:true,schema:new OA\Schema(type:'integer'))],responses:[new OA\Response(response:200,description:'OK'),new OA\Response(response:401,description:'No autenticado'),new OA\Response(response:403,description:'Sin permiso'),new OA\Response(response:404,description:'No encontrado'),new OA\Response(response:422,description:'Datos inválidos')])] public function renovar():void{}
#[OA\Patch(path:'/api/v1/membresias/{membresia}/suspender',summary:'suspender',description:'Permiso requerido: membresias.suspender.',security:[['sanctumBearer'=>[]]],tags:['Membresías'],parameters:[new OA\Parameter(name:'membresia',in:'path',required:true,schema:new OA\Schema(type:'integer'))],responses:[new OA\Response(response:200,description:'OK'),new OA\Response(response:401,description:'No autenticado'),new OA\Response(response:403,description:'Sin permiso'),new OA\Response(response:404,description:'No encontrado'),new OA\Response(response:422,description:'Datos inválidos')])] public function suspender():void{}
}