<?php
namespace App\OpenApi\Paths;
use OpenApi\Attributes as OA;
class MetodoPagoPaths {
#[OA\Get(path:'/api/v1/metodos-pago',summary:'index',description:'Permiso requerido: metodos_pago.ver.',security:[['sanctumBearer'=>[]]],tags:['Métodos de Pago'],responses:[new OA\Response(response:200,description:'OK'),new OA\Response(response:401,description:'No autenticado'),new OA\Response(response:403,description:'Sin permiso')])] public function index():void{}
#[OA\Post(path:'/api/v1/metodos-pago',summary:'store',description:'Permiso requerido: metodos_pago.crear.',security:[['sanctumBearer'=>[]]],tags:['Métodos de Pago'], requestBody:new OA\RequestBody(required:true,content:new OA\JsonContent(type:'object')),responses:[new OA\Response(response:200,description:'OK'),new OA\Response(response:401,description:'No autenticado'),new OA\Response(response:403,description:'Sin permiso')])] public function store():void{}
#[OA\Get(path:'/api/v1/metodos-pago/{metodoPago}',summary:'show',description:'Permiso requerido: metodos_pago.ver.',security:[['sanctumBearer'=>[]]],tags:['Métodos de Pago'], parameters:[new OA\Parameter(name:'metodoPago',in:'path',required:true,schema:new OA\Schema(type:'integer'))],responses:[new OA\Response(response:200,description:'OK'),new OA\Response(response:401,description:'No autenticado'),new OA\Response(response:403,description:'Sin permiso')])] public function show():void{}
#[OA\Put(path:'/api/v1/metodos-pago/{metodoPago}',summary:'updatePut',description:'Permiso requerido: metodos_pago.editar.',security:[['sanctumBearer'=>[]]],tags:['Métodos de Pago'], parameters:[new OA\Parameter(name:'metodoPago',in:'path',required:true,schema:new OA\Schema(type:'integer'))], requestBody:new OA\RequestBody(required:true,content:new OA\JsonContent(type:'object')),responses:[new OA\Response(response:200,description:'OK'),new OA\Response(response:401,description:'No autenticado'),new OA\Response(response:403,description:'Sin permiso')])] public function updatePut():void{}
#[OA\Patch(path:'/api/v1/metodos-pago/{metodoPago}',summary:'updatePatch',description:'Permiso requerido: metodos_pago.editar.',security:[['sanctumBearer'=>[]]],tags:['Métodos de Pago'], parameters:[new OA\Parameter(name:'metodoPago',in:'path',required:true,schema:new OA\Schema(type:'integer'))], requestBody:new OA\RequestBody(required:true,content:new OA\JsonContent(type:'object')),responses:[new OA\Response(response:200,description:'OK'),new OA\Response(response:401,description:'No autenticado'),new OA\Response(response:403,description:'Sin permiso')])] public function updatePatch():void{}
#[OA\Patch(path:'/api/v1/metodos-pago/{metodoPago}/desactivar',summary:'desactivar',description:'Permiso requerido: metodos_pago.desactivar.',security:[['sanctumBearer'=>[]]],tags:['Métodos de Pago'], parameters:[new OA\Parameter(name:'metodoPago',in:'path',required:true,schema:new OA\Schema(type:'integer'))],responses:[new OA\Response(response:200,description:'OK'),new OA\Response(response:401,description:'No autenticado'),new OA\Response(response:403,description:'Sin permiso')])] public function desactivar():void{}
#[OA\Patch(path:'/api/v1/metodos-pago/{metodoPago}/reactivar',summary:'reactivar',description:'Permiso requerido: metodos_pago.editar.',security:[['sanctumBearer'=>[]]],tags:['Métodos de Pago'], parameters:[new OA\Parameter(name:'metodoPago',in:'path',required:true,schema:new OA\Schema(type:'integer'))],responses:[new OA\Response(response:200,description:'OK'),new OA\Response(response:401,description:'No autenticado'),new OA\Response(response:403,description:'Sin permiso')])] public function reactivar():void{}
}