<?php
namespace App\OpenApi\Paths;
use OpenApi\Attributes as OA;
class PlanPaths {
#[OA\Get(path:'/api/v1/planes',summary:'index',description:'Permiso requerido: planes.ver.',security:[['sanctumBearer'=>[]]],tags:['Planes'],responses:[new OA\Response(response:200,description:'OK'),new OA\Response(response:401,description:'No autenticado'),new OA\Response(response:403,description:'Sin permiso')])] public function index():void{}
#[OA\Post(path:'/api/v1/planes',summary:'store',description:'Permiso requerido: planes.crear.',security:[['sanctumBearer'=>[]]],tags:['Planes'], requestBody:new OA\RequestBody(required:true,content:new OA\JsonContent(type:'object')),responses:[new OA\Response(response:200,description:'OK'),new OA\Response(response:401,description:'No autenticado'),new OA\Response(response:403,description:'Sin permiso')])] public function store():void{}
#[OA\Get(path:'/api/v1/planes/{plan}',summary:'show',description:'Permiso requerido: planes.ver.',security:[['sanctumBearer'=>[]]],tags:['Planes'], parameters:[new OA\Parameter(name:'plan',in:'path',required:true,schema:new OA\Schema(type:'integer'))],responses:[new OA\Response(response:200,description:'OK'),new OA\Response(response:401,description:'No autenticado'),new OA\Response(response:403,description:'Sin permiso')])] public function show():void{}
#[OA\Put(path:'/api/v1/planes/{plan}',summary:'updatePut',description:'Permiso requerido: planes.editar.',security:[['sanctumBearer'=>[]]],tags:['Planes'], parameters:[new OA\Parameter(name:'plan',in:'path',required:true,schema:new OA\Schema(type:'integer'))], requestBody:new OA\RequestBody(required:true,content:new OA\JsonContent(type:'object')),responses:[new OA\Response(response:200,description:'OK'),new OA\Response(response:401,description:'No autenticado'),new OA\Response(response:403,description:'Sin permiso')])] public function updatePut():void{}
#[OA\Patch(path:'/api/v1/planes/{plan}',summary:'updatePatch',description:'Permiso requerido: planes.editar.',security:[['sanctumBearer'=>[]]],tags:['Planes'], parameters:[new OA\Parameter(name:'plan',in:'path',required:true,schema:new OA\Schema(type:'integer'))], requestBody:new OA\RequestBody(required:true,content:new OA\JsonContent(type:'object')),responses:[new OA\Response(response:200,description:'OK'),new OA\Response(response:401,description:'No autenticado'),new OA\Response(response:403,description:'Sin permiso')])] public function updatePatch():void{}
#[OA\Patch(path:'/api/v1/planes/{plan}/desactivar',summary:'desactivar',description:'Permiso requerido: planes.desactivar.',security:[['sanctumBearer'=>[]]],tags:['Planes'], parameters:[new OA\Parameter(name:'plan',in:'path',required:true,schema:new OA\Schema(type:'integer'))],responses:[new OA\Response(response:200,description:'OK'),new OA\Response(response:401,description:'No autenticado'),new OA\Response(response:403,description:'Sin permiso')])] public function desactivar():void{}
#[OA\Patch(path:'/api/v1/planes/{plan}/reactivar',summary:'reactivar',description:'Permiso requerido: planes.editar.',security:[['sanctumBearer'=>[]]],tags:['Planes'], parameters:[new OA\Parameter(name:'plan',in:'path',required:true,schema:new OA\Schema(type:'integer'))],responses:[new OA\Response(response:200,description:'OK'),new OA\Response(response:401,description:'No autenticado'),new OA\Response(response:403,description:'Sin permiso')])] public function reactivar():void{}
}