<?php
namespace App\OpenApi\Paths;
use OpenApi\Attributes as OA;
class ReportePaths {
#[OA\Get(path:'/api/v1/reportes/dashboard',summary:'dashboard',description:'Permiso requerido: reportes.ver.',security:[['sanctumBearer'=>[]]],tags:['Reportes'],responses:[new OA\Response(response:200,description:'OK'),new OA\Response(response:401,description:'No autenticado'),new OA\Response(response:403,description:'Sin permiso'),new OA\Response(response:404,description:'No encontrado'),new OA\Response(response:422,description:'Datos inválidos')])] public function dashboard():void{}
#[OA\Get(path:'/api/v1/reportes/ingresos',summary:'ingresos',description:'Permiso requerido: reportes.ver.',security:[['sanctumBearer'=>[]]],tags:['Reportes'],responses:[new OA\Response(response:200,description:'OK'),new OA\Response(response:401,description:'No autenticado'),new OA\Response(response:403,description:'Sin permiso'),new OA\Response(response:404,description:'No encontrado'),new OA\Response(response:422,description:'Datos inválidos')])] public function ingresos():void{}
#[OA\Get(path:'/api/v1/reportes/ingresos/exportar',summary:'exportarIngresos',description:'Permiso requerido: reportes.exportar.',security:[['sanctumBearer'=>[]]],tags:['Reportes'],responses:[new OA\Response(response:200,description:'OK'),new OA\Response(response:401,description:'No autenticado'),new OA\Response(response:403,description:'Sin permiso'),new OA\Response(response:404,description:'No encontrado'),new OA\Response(response:422,description:'Datos inválidos')])] public function exportarIngresos():void{}
#[OA\Get(path:'/api/v1/reportes/accesos',summary:'accesos',description:'Permiso requerido: reportes.ver.',security:[['sanctumBearer'=>[]]],tags:['Reportes'],responses:[new OA\Response(response:200,description:'OK'),new OA\Response(response:401,description:'No autenticado'),new OA\Response(response:403,description:'Sin permiso'),new OA\Response(response:404,description:'No encontrado'),new OA\Response(response:422,description:'Datos inválidos')])] public function accesos():void{}
#[OA\Get(path:'/api/v1/reportes/accesos/exportar',summary:'exportarAccesos',description:'Permiso requerido: reportes.exportar.',security:[['sanctumBearer'=>[]]],tags:['Reportes'],responses:[new OA\Response(response:200,description:'OK'),new OA\Response(response:401,description:'No autenticado'),new OA\Response(response:403,description:'Sin permiso'),new OA\Response(response:404,description:'No encontrado'),new OA\Response(response:422,description:'Datos inválidos')])] public function exportarAccesos():void{}
#[OA\Get(path:'/api/v1/reportes/clientes',summary:'clientes',description:'Permiso requerido: reportes.ver.',security:[['sanctumBearer'=>[]]],tags:['Reportes'],responses:[new OA\Response(response:200,description:'OK'),new OA\Response(response:401,description:'No autenticado'),new OA\Response(response:403,description:'Sin permiso'),new OA\Response(response:404,description:'No encontrado'),new OA\Response(response:422,description:'Datos inválidos')])] public function clientes():void{}
#[OA\Get(path:'/api/v1/reportes/clientes-vencidos',summary:'clientesVencidos',description:'Permiso requerido: reportes.ver.',security:[['sanctumBearer'=>[]]],tags:['Reportes'],responses:[new OA\Response(response:200,description:'OK'),new OA\Response(response:401,description:'No autenticado'),new OA\Response(response:403,description:'Sin permiso'),new OA\Response(response:404,description:'No encontrado'),new OA\Response(response:422,description:'Datos inválidos')])] public function clientesVencidos():void{}
#[OA\Get(path:'/api/v1/reportes/clientes-vencidos/exportar',summary:'exportarClientesVencidos',description:'Permiso requerido: reportes.exportar.',security:[['sanctumBearer'=>[]]],tags:['Reportes'],responses:[new OA\Response(response:200,description:'OK'),new OA\Response(response:401,description:'No autenticado'),new OA\Response(response:403,description:'Sin permiso'),new OA\Response(response:404,description:'No encontrado'),new OA\Response(response:422,description:'Datos inválidos')])] public function exportarClientesVencidos():void{}
#[OA\Get(path:'/api/v1/reportes/membresias-por-vencer',summary:'membresiasPorVencer',description:'Permiso requerido: reportes.ver.',security:[['sanctumBearer'=>[]]],tags:['Reportes'],responses:[new OA\Response(response:200,description:'OK'),new OA\Response(response:401,description:'No autenticado'),new OA\Response(response:403,description:'Sin permiso'),new OA\Response(response:404,description:'No encontrado'),new OA\Response(response:422,description:'Datos inválidos')])] public function membresiasPorVencer():void{}
#[OA\Get(path:'/api/v1/reportes/membresias-por-vencer/exportar',summary:'exportarMembresiasPorVencer',description:'Permiso requerido: reportes.exportar.',security:[['sanctumBearer'=>[]]],tags:['Reportes'],responses:[new OA\Response(response:200,description:'OK'),new OA\Response(response:401,description:'No autenticado'),new OA\Response(response:403,description:'Sin permiso'),new OA\Response(response:404,description:'No encontrado'),new OA\Response(response:422,description:'Datos inválidos')])] public function exportarMembresiasPorVencer():void{}
}