<?php
namespace App\OpenApi\Paths; use OpenApi\Attributes as OA;
class SucursalPaths {
#[OA\Get(path:'/api/v1/sucursales',summary:'Listar sucursales',description:'Permiso requerido: sucursales.ver.',security:[['sanctumBearer'=>[]]],tags:['Sucursales'],responses:[new OA\Response(response:200,description:'Sucursales obtenidas'),new OA\Response(response:401,description:'No autenticado'),new OA\Response(response:403,description:'Sin permiso')])] public function index():void{}
#[OA\Post(path:'/api/v1/sucursales',summary:'Crear sucursal',description:'Permiso requerido: sucursales.crear.',security:[['sanctumBearer'=>[]]],tags:['Sucursales'],requestBody:new OA\RequestBody(required:true,content:new OA\JsonContent(type:'object')),responses:[new OA\Response(response:201,description:'Sucursal creada'),new OA\Response(response:401,description:'No autenticado'),new OA\Response(response:403,description:'Sin permiso'),new OA\Response(response:422,description:'Datos inválidos')])] public function store():void{}
#[OA\Get(path:'/api/v1/sucursales/{sucursal}',summary:'Ver sucursal',description:'Permiso requerido: sucursales.ver.',security:[['sanctumBearer'=>[]]],tags:['Sucursales'],parameters:[new OA\Parameter(name:'sucursal',in:'path',required:true,schema:new OA\Schema(type:'integer'))],responses:[new OA\Response(response:200,description:'Sucursal obtenida'),new OA\Response(response:404,description:'No encontrada')])] public function show():void{}
#[OA\Put(path:'/api/v1/sucursales/{sucursal}',summary:'Actualizar sucursal (PUT)',description:'Permiso requerido: sucursales.editar.',security:[['sanctumBearer'=>[]]],tags:['Sucursales'],parameters:[new OA\Parameter(name:'sucursal',in:'path',required:true,schema:new OA\Schema(type:'integer'))],requestBody:new OA\RequestBody(required:true,content:new OA\JsonContent(type:'object')),responses:[new OA\Response(response:200,description:'Sucursal actualizada'),new OA\Response(response:422,description:'Datos inválidos')])] public function updatePut():void{}
#[OA\Patch(path:'/api/v1/sucursales/{sucursal}',summary:'Actualizar sucursal (PATCH)',description:'Permiso requerido: sucursales.editar.',security:[['sanctumBearer'=>[]]],tags:['Sucursales'],parameters:[new OA\Parameter(name:'sucursal',in:'path',required:true,schema:new OA\Schema(type:'integer'))],requestBody:new OA\RequestBody(required:true,content:new OA\JsonContent(type:'object')),responses:[new OA\Response(response:200,description:'Sucursal actualizada'),new OA\Response(response:422,description:'Datos inválidos')])] public function updatePatch():void{}
#[OA\Patch(path:'/api/v1/sucursales/{sucursal}/desactivar',summary:'Desactivar sucursal',description:'Permiso requerido: sucursales.desactivar.',security:[['sanctumBearer'=>[]]],tags:['Sucursales'],parameters:[new OA\Parameter(name:'sucursal',in:'path',required:true,schema:new OA\Schema(type:'integer'))],responses:[new OA\Response(response:200,description:'Sucursal desactivada')])] public function desactivar():void{}
#[OA\Patch(path:'/api/v1/sucursales/{sucursal}/reactivar',summary:'Reactivar sucursal',description:'Permiso requerido: sucursales.editar.',security:[['sanctumBearer'=>[]]],tags:['Sucursales'],parameters:[new OA\Parameter(name:'sucursal',in:'path',required:true,schema:new OA\Schema(type:'integer'))],responses:[new OA\Response(response:200,description:'Sucursal reactivada')])] public function reactivar():void{}
}
