<?php

namespace App\OpenApi;

/**
 * @OA\PathItem(path="/api/v1/auth/login",
 *   @OA\Post(tags={"Auth"}, summary="Login", @OA\RequestBody(required=true, @OA\JsonContent(required={"login","password"}, @OA\Property(property="login", type="string", example="admin@sistemagym.local"), @OA\Property(property="password", type="string", format="password", example="password"))), @OA\Response(response=200, description="OK", @OA\JsonContent(ref="#/components/schemas/AuthResponse")), @OA\Response(response=422, description="Validation", @OA\JsonContent(ref="#/components/schemas/ValidationError422")))
 * )
 * @OA\PathItem(path="/api/v1/auth/me", @OA\Get(tags={"Auth"}, security={{"sanctumBearer":{}}}, summary="Usuario autenticado", description="Requiere Bearer Token Sanctum.", @OA\Response(response=200, description="OK"), @OA\Response(response=401, description="No autenticado", @OA\JsonContent(ref="#/components/schemas/Error401"))))
 * @OA\PathItem(path="/api/v1/auth/logout", @OA\Post(tags={"Auth"}, security={{"sanctumBearer":{}}}, summary="Cerrar sesión", @OA\Response(response=200, description="OK"), @OA\Response(response=401, description="No autenticado", @OA\JsonContent(ref="#/components/schemas/Error401"))))
 * @OA\PathItem(path="/api/v1/rbac/check-admin", @OA\Get(tags={"RBAC"}, security={{"sanctumBearer":{}}}, summary="Check admin", description="Permiso: roles.asignar_permisos", @OA\Response(response=200, description="Autorizado", @OA\JsonContent(@OA\Property(property="message", type="string", example="Autorizado correctamente."))), @OA\Response(response=403, description="Sin permiso", @OA\JsonContent(ref="#/components/schemas/Error403"))))
 *
 * @OA\PathItem(path="/api/v1/sucursales")
 * @OA\PathItem(path="/api/v1/sucursales/{sucursal}")
 * @OA\PathItem(path="/api/v1/sucursales/{sucursal}/desactivar")
 * @OA\PathItem(path="/api/v1/sucursales/{sucursal}/reactivar")
 * @OA\PathItem(path="/api/v1/planes")
 * @OA\PathItem(path="/api/v1/planes/{plan}")
 * @OA\PathItem(path="/api/v1/planes/{plan}/desactivar")
 * @OA\PathItem(path="/api/v1/planes/{plan}/reactivar")
 * @OA\PathItem(path="/api/v1/metodos-pago")
 * @OA\PathItem(path="/api/v1/metodos-pago/{metodoPago}")
 * @OA\PathItem(path="/api/v1/metodos-pago/{metodoPago}/desactivar")
 * @OA\PathItem(path="/api/v1/metodos-pago/{metodoPago}/reactivar")
 * @OA\PathItem(path="/api/v1/clientes")
 * @OA\PathItem(path="/api/v1/clientes/{cliente}")
 * @OA\PathItem(path="/api/v1/clientes/{cliente}/cambiar-estatus")
 * @OA\PathItem(path="/api/v1/clientes/{cliente}/desactivar")
 * @OA\PathItem(path="/api/v1/clientes/{cliente}/reactivar")
 * @OA\PathItem(path="/api/v1/clientes/{cliente}/membresias")
 * @OA\PathItem(path="/api/v1/clientes/{cliente}/pagos")
 * @OA\PathItem(path="/api/v1/clientes/{cliente}/accesos")
 * @OA\PathItem(path="/api/v1/clientes/{cliente}/biometricos")
 * @OA\PathItem(path="/api/v1/membresias")
 * @OA\PathItem(path="/api/v1/membresias/{membresia}")
 * @OA\PathItem(path="/api/v1/membresias/{membresia}/renovar")
 * @OA\PathItem(path="/api/v1/membresias/{membresia}/suspender")
 * @OA\PathItem(path="/api/v1/membresias/{membresia}/cancelar")
 * @OA\PathItem(path="/api/v1/membresias/{membresia}/reactivar")
 * @OA\PathItem(path="/api/v1/pagos")
 * @OA\PathItem(path="/api/v1/pagos/{pago}")
 * @OA\PathItem(path="/api/v1/pagos/{pago}/cancelar")
 * @OA\PathItem(path="/api/v1/accesos")
 * @OA\PathItem(path="/api/v1/accesos/{acceso}")
 * @OA\PathItem(path="/api/v1/accesos/validar")
 * @OA\PathItem(path="/api/v1/dispositivos")
 * @OA\PathItem(path="/api/v1/dispositivos/{dispositivo}")
 * @OA\PathItem(path="/api/v1/dispositivos/{dispositivo}/cambiar-estatus")
 * @OA\PathItem(path="/api/v1/dispositivos/{dispositivo}/desactivar")
 * @OA\PathItem(path="/api/v1/dispositivos/{dispositivo}/reactivar")
 * @OA\PathItem(path="/api/v1/biometricos")
 * @OA\PathItem(path="/api/v1/biometricos/{biometrico}")
 * @OA\PathItem(path="/api/v1/biometricos/enrolar")
 * @OA\PathItem(path="/api/v1/biometricos/{biometrico}/marcar-principal")
 * @OA\PathItem(path="/api/v1/biometricos/{biometrico}/desactivar")
 * @OA\PathItem(path="/api/v1/biometricos/{biometrico}/revocar")
 * @OA\PathItem(path="/api/v1/recepcion/clientes/buscar")
 * @OA\PathItem(path="/api/v1/recepcion/clientes/{cliente}/resumen")
 * @OA\PathItem(path="/api/v1/reportes/dashboard")
 * @OA\PathItem(path="/api/v1/reportes/ingresos")
 * @OA\PathItem(path="/api/v1/reportes/membresias-por-vencer")
 * @OA\PathItem(path="/api/v1/reportes/clientes-vencidos")
 * @OA\PathItem(path="/api/v1/reportes/accesos")
 * @OA\PathItem(path="/api/v1/reportes/clientes")
 * @OA\PathItem(path="/api/v1/reportes/ingresos/exportar")
 * @OA\PathItem(path="/api/v1/reportes/accesos/exportar")
 * @OA\PathItem(path="/api/v1/reportes/membresias-por-vencer/exportar")
 * @OA\PathItem(path="/api/v1/reportes/clientes-vencidos/exportar")
 * @OA\PathItem(path="/api/v1/cortes-caja")
 * @OA\PathItem(path="/api/v1/cortes-caja/calcular")
 * @OA\PathItem(path="/api/v1/cortes-caja/{corte}")
 * @OA\PathItem(path="/api/v1/cortes-caja/{corte}/cancelar")
 * @OA\PathItem(path="/api/v1/cortes-caja/{corte}/exportar")
 * @OA\PathItem(path="/api/v1/auditoria")
 * @OA\PathItem(path="/api/v1/auditoria/{evento}")
 */
class V1Paths {}
