<?php

namespace App\Enums;

enum AccesoMotivoRechazo: string
{
    case NINGUNO = 'NINGUNO';
    case CLIENTE_NO_EXISTE = 'CLIENTE_NO_EXISTE';
    case CLIENTE_INACTIVO = 'CLIENTE_INACTIVO';
    case CLIENTE_SUSPENDIDO = 'CLIENTE_SUSPENDIDO';
    case CLIENTE_BLOQUEADO = 'CLIENTE_BLOQUEADO';
    case MEMBRESIA_INEXISTENTE = 'MEMBRESIA_INEXISTENTE';
    case MEMBRESIA_VENCIDA = 'MEMBRESIA_VENCIDA';
    case MEMBRESIA_SUSPENDIDA = 'MEMBRESIA_SUSPENDIDA';
    case SIN_ACCESOS_DISPONIBLES = 'SIN_ACCESOS_DISPONIBLES';
    case SUCURSAL_NO_PERMITIDA = 'SUCURSAL_NO_PERMITIDA';
    case HUELLA_NO_COINCIDE = 'HUELLA_NO_COINCIDE';
    case ERROR_VALIDACION = 'ERROR_VALIDACION';
}
